# /images/本地路径为：source/images，本地source/文件夹渲染后对应网络路径为/
favicon: /favicon.ico
# Change to your profile picture
avatar: /images/profile.png
# if author sets in hexo_config, this string doesn't work
author: 'Jason'
author_bio: 'Your biography can be writed down here.'

since: 2022

# Top Menu 顶部菜单
# #title 为页内跳转，单页模式
# 可以配置为外链或其他页面
menu:
  Publications: /#Publications  #链接到一个标题锚点
  Introduction: /#Introduction
  Configurtion: /#Theme-Configurtion #带空格标题锚点需要添加‘-’替代空格路径
  About: /about/  #链接到一个页面
  Blog: https://yiwangmeng.cn
  Guide: https://yiwangmeng.com #外链


# flink picture will load if avator link calls on error
loading_bg:
  flink: /images/profile.png

# Social Links; 社交链接，不需要的链接直接注释掉
# 可以调整显示顺序
# 图标调用 font-awesome 4.7
social:
  enable: true
social_links:
  fab fa-twitter: /
  fab fa-facebook-square: /
  fab fa-github: /
  fab fa-stack-overflow: /
  fab fa-linkedin: /
  fab fa-weibo: /
  fab fa-weixin: /
  fab fa-qq: /
  fas fa-envelope: "mailto:xx@yy.zz" #E-mail
  fas fa-rss: /  #rss

# Additional social_links，额外添加自定义链接，可显示链接名称
# name: url || icon_name
e_social:
  enable: true
e_social_links:
  Google Scholar: / || fas fa-graduation-cap
  ORCID: / || fab fa-orcid

# CV download link
cv_dl:
  enable: true
  dir: /attaches/CV.pdf
  description: My Detail CV.

# Box-shadow
# display box-shadow on page or not
box_shadow:
  enable: false

# CDN
# 根据需要自行添加js/css
# 自定义css可以直接写在user.styl中
CDN_USE:
  css:
    - /css/index.css
    # - https://fastly.jsdelivr.net/npm/font-awesome@latest/css/font-awesome.min.css
    # - https://fastly.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.13.0/css/all.min.css # fontawesome 5
    - https://cdn.staticfile.org/font-awesome/6.4.2/css/all.min.css
  js:
    - /js/main.js
    # - https://fastly.jsdelivr.net/npm/jquery@latest/dist/jquery.min.js #/js/third-party/jquery.min.js
    # - https://fastly.jsdelivr.net/npm/jquery-pjax@latest/jquery.pjax.min.js
    - https://cdn.staticfile.org/jquery/3.7.1/jquery.min.js
    - https://cdn.staticfile.org/jquery.pjax/2.0.1/jquery.pjax.min.js